title: Metric Note
description: 통계와 LLM을 공부하며 이해한 과정을 기록하는 노트
lang: ko-KR
url: https://metricnote.github.io
remote_theme: andreondra/jekyll-theme-simplex
plugins:
  - jekyll-remote-theme
permalink: /:categories/:year/:month/:day/:title/
copyright: © Metric Note 2026
global_tags: data analysis statistics LLM transformer learning note
sass:
  style: compressed
collections:
  category:
    output: true
  authors:
    output: false
defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: category
