title: Metric Note
description: AI 기술을 탐구하고 실제 서비스에 적용하는 과정을 기록합니다.
lang: ko-KR
url: https://metricnote.github.io
remote_theme: andreondra/jekyll-theme-simplex
plugins:
  - jekyll-remote-theme
permalink: /:categories/:year/:month/:day/:title/
copyright: © Metric Note 2026
global_tags: data analysis statistics LLM transformer learning note
sass:
  style: compressed
collections:
  category:
    output: true
  authors:
    output: false
defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: category
